-- MySQL Script generated by MySQL Workbench
-- 06/28/20 19:32:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logistique_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistique_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistique_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `logistique_db` ;

-- -----------------------------------------------------
-- Table `logistique_db`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  `id_categorie` INT NULL,
  `emballage` VARCHAR(45) NULL,
  `nbe_pieces` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categ_idx` (`id_categorie` ASC),
  CONSTRAINT `fk_categ`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `logistique_db`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`sous_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`sous_categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`batiments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`batiments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_batiment` INT NULL,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bat_idx` (`id_batiment` ASC),
  CONSTRAINT `fk_bat`
    FOREIGN KEY (`id_batiment`)
    REFERENCES `logistique_db`.`batiments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`equipement` (
  `id` INT NOT NULL,
  `code_equipement` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `marque` VARCHAR(45) NULL,
  `etat` TINYINT(1) NULL,
  `id_article` INT NULL,
  `id_sous_categorie` INT NULL,
  `id_local` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_idx` (`id_article` ASC),
  INDEX `fk_sc_idx` (`id_sous_categorie` ASC),
  INDEX `fk_loc_idx` (`id_local` ASC),
  CONSTRAINT `fk_article`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sc`
    FOREIGN KEY (`id_sous_categorie`)
    REFERENCES `logistique_db`.`sous_categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loc`
    FOREIGN KEY (`id_local`)
    REFERENCES `logistique_db`.`local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`consommable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`consommable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_article` INT NULL,
  `date_peremption` DATE NULL,
  `etat` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_cons_idx` (`id_article` ASC),
  CONSTRAINT `fk_article_cons`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  `cout` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`demandeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`demandeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`demande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_demande` DATE NULL,
  `numero_demande` VARCHAR(45) NULL,
  `id_demandeur` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `demanduer_idx` (`id_demandeur` ASC),
  CONSTRAINT `demanduer`
    FOREIGN KEY (`id_demandeur`)
    REFERENCES `logistique_db`.`demandeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`ligne_demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`ligne_demande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `motif_demande` VARCHAR(45) NULL,
  `quantite` INT NULL,
  `id_article` INT NULL,
  `id_service` INT NULL,
  `id_demande` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_art_idx` (`id_article` ASC),
  INDEX `fk_servide_idx` (`id_service` ASC),
  INDEX `fldmd_idx` (`id_demande` ASC),
  CONSTRAINT `fk_art`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servide`
    FOREIGN KEY (`id_service`)
    REFERENCES `logistique_db`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fldmd`
    FOREIGN KEY (`id_demande`)
    REFERENCES `logistique_db`.`demande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATE NULL,
  `id_demande` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkdm_idx` (`id_demande` ASC),
  CONSTRAINT `fkdm`
    FOREIGN KEY (`id_demande`)
    REFERENCES `logistique_db`.`demande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`ligne_commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `montant_cmd` INT NULL,
  `id_commande` INT NULL,
  `qte_cmd` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkcmd`
    FOREIGN KEY (`id_commande`)
    REFERENCES `logistique_db`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`livraisons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`livraisons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `montant_livraison` INT NULL,
  `date_livraison` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`commande_livrer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`commande_livrer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_livraison` INT NULL,
  `id_commande` INT NULL,
  `date_livraison` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_liv_idx` (`id_livraison` ASC),
  INDEX `fk_cmd_idx` (`id_commande` ASC),
  CONSTRAINT `fk_liv`
    FOREIGN KEY (`id_livraison`)
    REFERENCES `logistique_db`.`livraisons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cmd`
    FOREIGN KEY (`id_commande`)
    REFERENCES `logistique_db`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`receptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`receptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receptionscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`reception_livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`reception_livraison` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_livraison` INT NULL,
  `id_reception` INT NULL,
  `date_recep` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recep_idx` (`id_reception` ASC),
  INDEX `fk_livra_idx` (`id_livraison` ASC),
  CONSTRAINT `fk_recep`
    FOREIGN KEY (`id_reception`)
    REFERENCES `logistique_db`.`receptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livra`
    FOREIGN KEY (`id_livraison`)
    REFERENCES `logistique_db`.`livraisons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`utilisateur_equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`utilisateur_equipement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`emprunts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`emprunts` (
  `id` INT NOT NULL,
  `id_user_equip` INT NULL,
  `id_equipement` INT NULL,
  `date_emprunt` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equi_idx` (`id_equipement` ASC),
  INDEX `fk_user_eq_idx` (`id_user_equip` ASC),
  CONSTRAINT `fk_equi`
    FOREIGN KEY (`id_equipement`)
    REFERENCES `logistique_db`.`equipement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_eq`
    FOREIGN KEY (`id_user_equip`)
    REFERENCES `logistique_db`.`utilisateur_equipement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`stocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_article` INT NULL,
  `qte_stock` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ar_idx` (`id_article` ASC),
  CONSTRAINT `fk_ar`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`achats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`achats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_achat` DATE NULL,
  `motif_achat` VARCHAR(45) NULL,
  `prix_article` INT NULL,
  `id_article` INT NULL,
  `qte_achat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fkart_idx` (`id_article` ASC),
  CONSTRAINT `fkart`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`sorties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`sorties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_sortie` DATE NULL,
  `qte_sortie` INT NULL,
  `id_article` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkarticle_idx` (`id_article` ASC),
  CONSTRAINT `fkarticle`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  `id_article` INT NULL,
  `qte_donnes` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkart_idx` (`id_article` ASC),
  CONSTRAINT `fkart`
    FOREIGN KEY (`id_article`)
    REFERENCES `logistique_db`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistique_db`.`utlisateur_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistique_db`.`utlisateur_app` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(175) NULL,
  `email` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
